# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: abce93a7a496199483eafe0b7693934e3326268d1ead8e7488c86e0ce3ced67a606308fd03f7ca9df00ca0c5a0bc9ca7e9d7647703028f5f226014b694a37461

test:
  secret_key_base: 1e222faac00bc0aa162a48e283140ebd50bac1bf84ad1451eec664a0f07563221cf873dfe0279ca51f34ae3f4caaff51c282c37f4b5776898d50b10f642a400c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
